### ISSUE TITLE
Errors in SAI ptf test

### ISSUE THREAD

**Issue by stephengzh** [opencomputeproject/SAI#1164]
Hello, I just built the SAI thrift-ptf. However, when I executed the ptf tests, all tests failed.
The detail is shown below, seems like all tests failed in "TTransportException: Transport not open". But I don't know why. May be I fogot some step in configurations? (The building steps provided in test/thrift/README.md looks  very old and is with a little bit unclear expressions, I try my best to follow the steps.) 

I config Ethernet1 with ip address 10.0.0.0 on my server, and Ethernet1 with ip address 10.0.0.1 on my client. Both server and client are sonic devices.
 
And I can ping from 10.0.0.0 to 10.0.0.1. 

Errors:

root@sai-client:/home/admin/SAI/test/saithrift# sudo ptf --test-dir tests saifdb.L2FDBMissUnicastTest --interface '1@Ethernet1' -t "server='10.0.0.0';port_map_file='src/portmaps/default_interface_to_front_map.ini'"
saifdb.L2FDBMissUnicastTest ... 09:52:34.377  thrift.transport.TSocket: ERROR   : Could not connect to any of [('10.0.0.0', 9092)]

Test FDB unicast miss action
ERROR
ERROR

======================================================================
ERROR: saifdb.L2FDBMissUnicastTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/saifdb.py", line 27, in runTest
    switch_init(self.client)
  File "tests/switch.py", line 76, in switch_init
    switch.default_1q_bridge = client.sai_thrift_get_default_1q_bridge_id()
  File "/usr/local/lib/python2.7/dist-packages/switch_sai_thrift/switch_sai_rpc.py", line 2248, in sai_thrift_get_default_1q_bridge_id
    self.send_sai_thrift_get_default_1q_bridge_id()
  File "/usr/local/lib/python2.7/dist-packages/switch_sai_thrift/switch_sai_rpc.py", line 2256, in send_sai_thrift_get_default_1q_bridge_id
    self._oprot.trans.flush()
  File "/usr/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 177, in flush
    self.__trans.write(out)
  File "/usr/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 138, in write
    message='Transport not open')
TTransportException: Transport not open

======================================================================
ERROR: saifdb.L2FDBMissUnicastTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/saifdb.py", line 67, in tearDown
    self.client.sai_thrift_flush_fdb_entries(thrift_attr_list=[])
  File "/usr/local/lib/python2.7/dist-packages/switch_sai_thrift/switch_sai_rpc.py", line 984, in sai_thrift_flush_fdb_entries
    self.send_sai_thrift_flush_fdb_entries(thrift_attr_list)
  File "/usr/local/lib/python2.7/dist-packages/switch_sai_thrift/switch_sai_rpc.py", line 993, in send_sai_thrift_flush_fdb_entries
    self._oprot.trans.flush()
  File "/usr/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 177, in flush
    self.__trans.write(out)
  File "/usr/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 138, in write
    message='Transport not open')
TTransportException: Transport not open

----------------------------------------------------------------------
Ran 1 test in 130.903s

FAILED (errors=2)
()
******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!
()
The following tests errored:
L2FDBMissUnicastTest, L2FDBMissUnicastTest
()
******************************************

**Comment by stephengzh** [comment]
@pavel-shirshov Can you check this issue? Thanks.

**Comment by richardyu-ms** [comment]
Yes, the saiserver environment is quite old, besides the updates here, some other documents also added at https://github.com/Azure/sonic-mgmt/tree/master/docs/testbed/sai_quality
thanks for your feedback.

@lguohan could you help close this issue?

**Comment by stephengao-ragilenetworks** [comment]
@richardyu-ms Thanks, it helps. This issue was opened by my previous account, may need an administrator to close it.

**Comment by richardyu-ms** [comment]
close this one. thanks for all.
